import { useEffect, useRef, useState } from "react";
import { AlertCircle, Loader2, Mic, Sparkles, Volume2 } from "lucide-react";
import {
  ElevenLabsTtsError,
  generateNarrationAudio,
  type ElevenLabsVoiceSettings,
} from "../lib/elevenlabs";
import { cn } from "../lib/utils";

interface NarrationStudioProps {
  /**
   * Narration script generated upstream by an LLM/agent. The text area is
   * pre-filled with this and remains editable so caregivers can tweak before
   * generating audio.
   */
  initialScript?: string;
  /** Optional pre-selected ElevenLabs voice ID (e.g. a cloned voice). */
  initialVoiceId?: string;
  /** Whether to expose the optional voice-ID input. Defaults to true. */
  showVoiceIdInput?: boolean;
  className?: string;
}

const SAMPLE_SCRIPT =
  "Hi Ellie, it's Sarah. Do you remember that Thanksgiving when you taught me to make your apple pie? The kitchen smelled like cinnamon for days, and the whole family kept sneaking pieces before dinner. You said the secret was a splash of cold water and a steady hand. I think about it every fall.";

export default function NarrationStudio({
  initialScript,
  initialVoiceId,
  showVoiceIdInput = true,
  className,
}: NarrationStudioProps) {
  const [scriptText, setScriptText] = useState(initialScript ?? SAMPLE_SCRIPT);
  const [voiceId, setVoiceId] = useState(initialVoiceId ?? "");
  const [audioUrl, setAudioUrl] = useState<string | null>(null);
  const [audioMeta, setAudioMeta] = useState<{ voiceId: string | null; modelId: string | null } | null>(
    null
  );
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const audioUrlRef = useRef<string | null>(null);
  useEffect(() => {
    audioUrlRef.current = audioUrl;
  }, [audioUrl]);

  useEffect(() => {
    return () => {
      if (audioUrlRef.current) {
        URL.revokeObjectURL(audioUrlRef.current);
      }
    };
  }, []);

  useEffect(() => {
    if (initialScript !== undefined) {
      setScriptText(initialScript);
    }
  }, [initialScript]);

  const handleGenerate = async () => {
    const trimmed = scriptText.trim();
    if (!trimmed) {
      setError("Please add a narration script first.");
      return;
    }

    setIsLoading(true);
    setError(null);

    try {
      const voiceSettings: ElevenLabsVoiceSettings = {
        stability: 0.5,
        similarity_boost: 0.75,
        style: 0,
        use_speaker_boost: true,
      };
      const result = await generateNarrationAudio({
        scriptText: trimmed,
        voiceId: voiceId.trim() || undefined,
        voiceSettings,
      });

      if (audioUrlRef.current) {
        URL.revokeObjectURL(audioUrlRef.current);
      }
      setAudioUrl(result.url);
      setAudioMeta({ voiceId: result.voiceId, modelId: result.modelId });
    } catch (err) {
      const message =
        err instanceof ElevenLabsTtsError
          ? err.message
          : err instanceof Error
            ? err.message
            : "Something went wrong while generating audio.";
      setError(message);
    } finally {
      setIsLoading(false);
    }
  };

  const charCount = scriptText.length;

  return (
    <div
      className={cn(
        "bg-posthog-sage dark:bg-slate-900 rounded-[2.5rem] p-8 border border-posthog-border/50 dark:border-slate-800 shadow-sm",
        className
      )}
    >
      <div className="flex items-center gap-3 mb-6">
        <div className="w-10 h-10 rounded-2xl bg-posthog-light-sage dark:bg-slate-800 flex items-center justify-center text-posthog-orange">
          <Mic size={20} />
        </div>
        <div>
          <h3 className="text-xl font-bold text-posthog-deep-ink dark:text-slate-100 tracking-tight">
            Narration Studio
          </h3>
          <p className="text-xs text-posthog-ink/70 dark:text-slate-500">
            Turn the final narration script into a natural voice with ElevenLabs.
          </p>
        </div>
      </div>

      <label
        htmlFor="narration-script"
        className="block text-xs font-bold uppercase tracking-wider text-posthog-ink/70 dark:text-slate-500 mb-2"
      >
        Narration Script
      </label>
      <textarea
        id="narration-script"
        value={scriptText}
        onChange={(event) => setScriptText(event.target.value)}
        rows={6}
        spellCheck={true}
        placeholder="Paste or edit the narration script generated by your LLM…"
        className={cn(
          "w-full resize-y rounded-2xl border border-posthog-border bg-posthog-parchment dark:bg-slate-950/40",
          "p-4 text-base leading-relaxed text-posthog-deep-ink dark:text-slate-100",
          "placeholder:text-posthog-ink/40 dark:placeholder:text-slate-600",
          "focus:outline-none focus:ring-2 focus:ring-posthog-cta/40"
        )}
      />
      <div className="mt-1 text-[11px] text-posthog-ink/60 dark:text-slate-500 text-right">
        {charCount.toLocaleString()} characters
      </div>

      {showVoiceIdInput && (
        <div className="mt-4">
          <label
            htmlFor="narration-voice-id"
            className="block text-xs font-bold uppercase tracking-wider text-posthog-ink/70 dark:text-slate-500 mb-2"
          >
            ElevenLabs Voice ID <span className="font-normal lowercase tracking-normal">(optional)</span>
          </label>
          <input
            id="narration-voice-id"
            type="text"
            value={voiceId}
            onChange={(event) => setVoiceId(event.target.value)}
            placeholder="Leave blank to use the default voice (ELEVENLABS_VOICE_ID)"
            className={cn(
              "w-full rounded-2xl border border-posthog-border bg-posthog-parchment dark:bg-slate-950/40",
              "p-3 text-sm text-posthog-deep-ink dark:text-slate-100",
              "placeholder:text-posthog-ink/40 dark:placeholder:text-slate-600",
              "focus:outline-none focus:ring-2 focus:ring-posthog-cta/40"
            )}
          />
          <p className="mt-2 text-[11px] leading-relaxed text-posthog-ink/60 dark:text-slate-500 flex items-start gap-1.5">
            <AlertCircle size={12} className="mt-0.5 shrink-0" />
            Cloned voices should only be used with the clear, documented consent of the person whose voice was cloned.
          </p>
        </div>
      )}

      <div className="mt-6 flex flex-wrap items-center gap-3">
        <button
          type="button"
          onClick={handleGenerate}
          disabled={isLoading || scriptText.trim().length === 0}
          className={cn(
            "inline-flex items-center gap-2 px-6 py-3 rounded-2xl text-sm font-bold transition-all shadow-md",
            "bg-posthog-cta text-white hover:bg-indigo-700",
            "disabled:opacity-60 disabled:cursor-not-allowed disabled:hover:bg-posthog-cta"
          )}
        >
          {isLoading ? (
            <>
              <Loader2 size={18} className="animate-spin" />
              Generating audio…
            </>
          ) : (
            <>
              <Sparkles size={18} />
              Generate Audio
            </>
          )}
        </button>

        {audioMeta?.voiceId && !isLoading && (
          <span className="text-[11px] uppercase tracking-wider font-bold text-posthog-ink/60 dark:text-slate-500">
            Voice: <span className="font-mono normal-case tracking-normal">{audioMeta.voiceId}</span>
            {audioMeta.modelId ? (
              <>
                {" "}· Model:{" "}
                <span className="font-mono normal-case tracking-normal">{audioMeta.modelId}</span>
              </>
            ) : null}
          </span>
        )}
      </div>

      {error && (
        <div
          role="alert"
          className="mt-4 flex items-start gap-3 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800 dark:border-rose-900/40 dark:bg-rose-950/30 dark:text-rose-200"
        >
          <AlertCircle size={18} className="mt-0.5 shrink-0" />
          <div>
            <p className="font-bold">Couldn't generate audio</p>
            <p className="opacity-90">{error}</p>
          </div>
        </div>
      )}

      {audioUrl && !error && (
        <div className="mt-6 rounded-2xl border border-posthog-border bg-posthog-parchment dark:bg-slate-950/40 p-4">
          <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-posthog-ink/70 dark:text-slate-500 mb-3">
            <Volume2 size={14} />
            Generated Narration
          </div>
          <audio src={audioUrl} controls className="w-full" />
          <div className="mt-3 flex flex-wrap gap-3 text-[11px] text-posthog-ink/60 dark:text-slate-500">
            <a
              href={audioUrl}
              download="narration.mp3"
              className="font-bold text-posthog-orange hover:underline"
            >
              Download MP3
            </a>
          </div>
        </div>
      )}
    </div>
  );
}
