// Hardcoded Robert Ellis demo content. No backend seed is required.

export const MOCK_PATIENT = {
  id: "p-robert",
  firstName: "Robert",
  lastName: "Ellis",
  preferredName: "Robert",
  dateOfBirth: "1948-03-18",
  diagnosisDate: "2024-01-12",
  dementiaType: "Alzheimer's",
  stage: "moderate" as const,
  programWeek: 4,
};

export const MOCK_MEMORIES = [
  {
    id: "mem-wedding",
    patientId: "p-robert",
    contributorId: "demo-caregiver",
    title: "The Wedding Day at St. Mary's Church",
    description:
      "Robert and Elaine got married in a small church with wooden pews, stained glass windows, soft organ music, and close family around them. Robert remembers Elaine walking down the aisle in a simple white dress while sunlight came through the windows.",
    patientDisplay:
      "Robert, this was the day you and Elaine began your life together. She walked toward you down the aisle, smiling, while your family watched from the pews.",
    type: "photo" as const,
    memoryTypeLabel: "Photo + voice story + future VR scene",
    lifePeriod: "young_adult" as const,
    emotionTags: ["loving", "joyful", "peaceful"],
    sensoryCues: ["Soft organ music", "fresh flowers", "polished wood", "warm sunlight"],
    therapeuticScore: 5,
    assetUrl: "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&q=80&w=1000",
    createdAt: "2026-04-25T10:00:00Z",
  },
  {
    id: "mem-pancakes",
    patientId: "p-robert",
    contributorId: "demo-caregiver",
    title: "Sunday Morning Pancakes",
    description:
      "Every Sunday, Robert made pancakes for Elaine and the kids while jazz played in the kitchen. He always made the first pancake too big and joked that it was the practice pancake.",
    patientDisplay:
      "Sunday mornings were your favorite. The kitchen smelled like pancakes and coffee, and Louis Armstrong played softly while your family sat around the table.",
    type: "photo" as const,
    memoryTypeLabel: "Photo + audio narrative",
    lifePeriod: "middle_age" as const,
    emotionTags: ["peaceful", "loving"],
    sensoryCues: ["Butter", "maple syrup", "coffee", "jazz music", "warm kitchen"],
    therapeuticScore: 5,
    assetUrl: "https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&q=80&w=1000",
    createdAt: "2026-04-25T10:05:00Z",
  },
  {
    id: "mem-classroom",
    patientId: "p-robert",
    contributorId: "demo-family",
    title: "Robert's First Classroom",
    description:
      "Robert taught high school history for 38 years. His classroom had maps, chalkboards, old books, and student projects on the walls. He used to say, History is just people's stories written down.",
    patientDisplay:
      "You were Mr. Ellis, the history teacher everyone remembered. Your classroom was full of maps, books, and students who listened to your stories.",
    type: "story" as const,
    memoryTypeLabel: "Photo + story",
    lifePeriod: "middle_age" as const,
    emotionTags: ["proud"],
    sensoryCues: ["Chalk dust", "old textbooks", "school bells", "paper", "wooden desks"],
    therapeuticScore: 5,
    assetUrl: "https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&q=80&w=1000",
    createdAt: "2026-04-25T10:10:00Z",
  },
  {
    id: "mem-boardwalk",
    patientId: "p-robert",
    contributorId: "demo-caregiver",
    title: "The Boardwalk Dance",
    description:
      "Robert first met Elaine at a summer boardwalk dance in 1973. He was nervous, but he asked her to dance anyway. Elaine later joked that he had two left feet, but she loved him from the beginning.",
    patientDisplay:
      "Robert, this is where you first asked Elaine to dance. You were nervous, but she smiled, and that dance became the beginning of everything.",
    type: "music" as const,
    memoryTypeLabel: "Music + voice story",
    lifePeriod: "young_adult" as const,
    emotionTags: ["loving", "joyful"],
    sensoryCues: ["Ocean breeze", "summer night air", "music", "boardwalk lights"],
    therapeuticScore: 5,
    assetUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=1000",
    createdAt: "2026-04-25T10:15:00Z",
  },
  {
    id: "mem-fishing",
    patientId: "p-robert",
    contributorId: "demo-family",
    title: "Fishing With His Son",
    description:
      "Robert used to take his son fishing at a quiet lake early in the morning. They would sit together, mostly silent, drinking coffee and waiting for the fish to bite.",
    patientDisplay:
      "You and your son spent quiet mornings by the lake. You taught him patience, how to cast a line, and how to enjoy silence together.",
    type: "photo" as const,
    memoryTypeLabel: "Photo + short video",
    lifePeriod: "middle_age" as const,
    emotionTags: ["peaceful", "loving"],
    sensoryCues: ["Lake water", "birds", "fishing line", "cool morning air", "thermos coffee"],
    therapeuticScore: 5,
    assetUrl: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&q=80&w=1000",
    createdAt: "2026-04-25T10:20:00Z",
  },
  {
    id: "mem-thanksgiving",
    patientId: "p-robert",
    contributorId: "demo-caregiver",
    title: "The Family Thanksgiving Table",
    description:
      "Thanksgiving was Robert's favorite holiday. He carved the turkey every year, told the same jokes, and always made sure everyone had enough food before serving himself.",
    patientDisplay:
      "Thanksgiving was your tradition. You stood at the head of the table, carving the turkey and smiling as your family gathered around you.",
    type: "photo" as const,
    memoryTypeLabel: "Photo gallery + sensory cue",
    lifePeriod: "middle_age" as const,
    emotionTags: ["joyful", "loving"],
    sensoryCues: ["Turkey", "cinnamon", "apple pie", "warm dining room", "family voices"],
    therapeuticScore: 5,
    assetUrl: "https://images.unsplash.com/photo-1540339832862-47459980783f?auto=format&fit=crop&q=80&w=1000",
    createdAt: "2026-04-25T10:25:00Z",
  },
  {
    id: "mem-living-room-dance",
    patientId: "p-robert",
    contributorId: "demo-caregiver",
    title: "Dancing in the Living Room",
    description:
      "Robert and Elaine often danced in the living room after dinner. Sometimes it was jazz, sometimes old love songs. Elaine says Robert always held her hand like it was their wedding day again.",
    patientDisplay:
      "Elaine remembers dancing with you in the living room after dinner. The music was soft, the lights were warm, and you always held her hand gently.",
    type: "music" as const,
    memoryTypeLabel: "Music + voice recording",
    lifePeriod: "middle_age" as const,
    emotionTags: ["loving", "peaceful"],
    sensoryCues: ["Soft music", "evening lamp light", "carpet underfoot", "quiet laughter"],
    therapeuticScore: 5,
    assetUrl: "https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&q=80&w=1000",
    createdAt: "2026-04-25T10:30:00Z",
  },
  {
    id: "mem-grandchildren",
    patientId: "p-robert",
    contributorId: "demo-family",
    title: "Grandchildren in the Backyard",
    description:
      "Robert loved watching his grandchildren run around the backyard. He would sit in his lawn chair, clap when they scored goals, and sneak them extra cookies when Elaine was not looking.",
    patientDisplay:
      "Your grandchildren loved playing in the backyard with you nearby. You cheered for them, laughed with them, and always made them feel special.",
    type: "photo" as const,
    memoryTypeLabel: "Photo + video",
    lifePeriod: "recent" as const,
    emotionTags: ["joyful", "funny", "loving"],
    sensoryCues: ["Fresh grass", "summer air", "children laughing", "cookies", "backyard sunlight"],
    therapeuticScore: 5,
    assetUrl: "https://images.unsplash.com/photo-1511895426328-dc8714191300?auto=format&fit=crop&q=80&w=1000",
    createdAt: "2026-04-25T10:35:00Z",
  },
  {
    id: "mem-retirement",
    patientId: "p-robert",
    contributorId: "demo-family",
    title: "Retirement Party",
    description:
      "When Robert retired, former students came back to thank him. One student told him that his history class made her want to become a teacher. Robert cried quietly when Elaine read the cards at home.",
    patientDisplay:
      "Your students came back to thank you because you changed their lives. You were not just a teacher. You were someone they remembered.",
    type: "story" as const,
    memoryTypeLabel: "Photo + written story",
    lifePeriod: "recent" as const,
    emotionTags: ["proud", "loving"],
    sensoryCues: ["Applause", "cake", "handwritten cards", "classroom decorations"],
    therapeuticScore: 5,
    assetUrl: "https://images.unsplash.com/photo-1523580494863-6f3031224c94?auto=format&fit=crop&q=80&w=1000",
    createdAt: "2026-04-25T10:40:00Z",
  },
  {
    id: "mem-morning-coffee",
    patientId: "p-robert",
    contributorId: "demo-caregiver",
    title: "Morning Coffee With Elaine",
    description:
      "Even after retirement, Robert and Elaine started every morning with coffee at the kitchen table. Elaine read the newspaper headlines, and Robert always asked for just one more splash of milk.",
    patientDisplay:
      "Every morning, you and Elaine sat together with coffee. The kitchen was quiet, the sunlight came through the window, and the day started with the two of you.",
    type: "story" as const,
    memoryTypeLabel: "Voice story + calming routine",
    lifePeriod: "recent" as const,
    emotionTags: ["peaceful", "loving"],
    sensoryCues: ["Coffee", "newspaper pages", "morning light", "ceramic mugs"],
    therapeuticScore: 5,
    assetUrl: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&q=80&w=1000",
    createdAt: "2026-04-25T10:45:00Z",
  },
];

export const MOCK_MOOD_LOGS = [
  { id: "l1", patientId: "p-robert", mood: "calm" as const, timestamp: "2026-04-20T09:00:00Z" },
  { id: "l2", patientId: "p-robert", mood: "happy" as const, timestamp: "2026-04-20T14:00:00Z" },
  { id: "l3", patientId: "p-robert", mood: "calm" as const, timestamp: "2026-04-21T10:00:00Z" },
  { id: "l4", patientId: "p-robert", mood: "happy" as const, timestamp: "2026-04-21T16:00:00Z" },
  { id: "l5", patientId: "p-robert", mood: "confused" as const, timestamp: "2026-04-22T08:30:00Z" },
];

export const AI_PROGRAM_WEEKS = [
  {
    week: 1,
    theme: "Safety and Familiar Faces",
    sourceMemories: ["Morning Coffee With Elaine", "Dancing in the Living Room"],
    therapySession: "Elaine voice story with quiet kitchen imagery and warm morning light.",
    collaboratorPrompt: "Invite Elaine or Michael to add a voice recording about Robert's morning routine.",
    aiReason: "The strongest calming anchors are Elaine's presence, coffee, soft light, and predictable daily rhythm.",
  },
  {
    week: 2,
    theme: "Young Love",
    sourceMemories: ["The Wedding Day at St. Mary's Church", "The Boardwalk Dance"],
    therapySession: "Photo and music session focused on Elaine walking down the aisle and the first boardwalk dance.",
    collaboratorPrompt: "Ask family for wedding photos, Elaine's favorite song from 1973, and boardwalk details.",
    aiReason: "Romantic memories carry high joy and identity value, with low agitation risk and strong sensory cues.",
  },
  {
    week: 3,
    theme: "Home and Sunday Routine",
    sourceMemories: ["Sunday Morning Pancakes", "Morning Coffee With Elaine"],
    therapySession: "Audio narrative with jazz, pancakes, coffee, and the practice pancake joke.",
    collaboratorPrompt: "Ask children to record a short line about Sunday breakfast at the kitchen table.",
    aiReason: "Repeated family routines are easy to recognize and help Robert feel oriented without heavy recall demands.",
  },
  {
    week: 4,
    theme: "Purpose and Pride",
    sourceMemories: ["Robert's First Classroom", "Retirement Party"],
    therapySession: "Story session about Mr. Ellis, the history teacher whose students remembered him.",
    collaboratorPrompt: "Invite former students or family to add quotes, classroom photos, or card excerpts.",
    aiReason: "Career memories reinforce dignity, competence, and identity beyond the diagnosis.",
  },
  {
    week: 5,
    theme: "Fatherhood and Quiet Bonding",
    sourceMemories: ["Fishing With His Son"],
    therapySession: "Calming lake scene with birds, cool air, thermos coffee, and patient silence.",
    collaboratorPrompt: "Ask Michael to add a fishing photo or short video from the lake.",
    aiReason: "The lake memory is peaceful and low stimulation, useful for anxiety or late-day agitation.",
  },
  {
    week: 6,
    theme: "Family Traditions",
    sourceMemories: ["The Family Thanksgiving Table", "Sunday Morning Pancakes"],
    therapySession: "Photo gallery plus sensory prompts around turkey, cinnamon, maple syrup, and family voices.",
    collaboratorPrompt: "Ask relatives to add one Thanksgiving detail Robert always repeated.",
    aiReason: "Food traditions combine strong smell/taste cues with belonging and role continuity.",
  },
  {
    week: 7,
    theme: "Music and Movement",
    sourceMemories: ["Dancing in the Living Room", "The Boardwalk Dance"],
    therapySession: "Gentle seated movement session with old love songs and Elaine's hand-holding narration.",
    collaboratorPrompt: "Ask Elaine for two songs that made Robert smile after dinner.",
    aiReason: "Music can cue movement and closeness even when verbal recall is limited.",
  },
  {
    week: 8,
    theme: "Grandchildren and Play",
    sourceMemories: ["Grandchildren in the Backyard"],
    therapySession: "Backyard photo/video session with children's laughter and cookie story.",
    collaboratorPrompt: "Invite grandchildren to contribute 10-second voice notes for Robert.",
    aiReason: "Grandchildren memories create joy and playfulness while reinforcing Robert's family role.",
  },
  {
    week: 9,
    theme: "Legacy",
    sourceMemories: ["Retirement Party", "Robert's First Classroom"],
    therapySession: "Legacy story: students returned because Robert changed their lives.",
    collaboratorPrompt: "Ask family to add cards, student names, and one teaching phrase Robert used.",
    aiReason: "Legacy content is ideal for caregiver/facility staff because it explains what Robert is proud of.",
  },
  {
    week: 10,
    theme: "Comfort Plan",
    sourceMemories: ["Morning Coffee With Elaine", "Fishing With His Son", "Dancing in the Living Room"],
    therapySession: "Low-stimulation care plan: coffee, lake water, soft music, warm lamp light.",
    collaboratorPrompt: "Ask caregivers which sensory cues calm Robert fastest during confusion.",
    aiReason: "The AI clusters peaceful cues into a practical de-escalation toolkit.",
  },
  {
    week: 11,
    theme: "The Story Robert Should Hear",
    sourceMemories: ["The Wedding Day at St. Mary's Church", "Retirement Party", "Grandchildren in the Backyard"],
    therapySession: "Long-form voice story celebrating Robert as husband, teacher, father, and grandfather.",
    collaboratorPrompt: "Invite everyone to add one sentence beginning, 'Robert, I want you to know...'",
    aiReason: "This week compiles identity anchors into one affirming narrative.",
  },
  {
    week: 12,
    theme: "Bridge Document Ready",
    sourceMemories: ["All approved memories"],
    therapySession: "Complete profile package for home, PT/care team, and facility handoff.",
    collaboratorPrompt: "Caregiver reviews the AI summary and chooses who receives it.",
    aiReason: "The final week converts memory content into continuity-of-care instructions.",
  },
];

export const BRIDGE_SUMMARY = {
  title: "AI Bridge Summary for Robert Ellis",
  status: "Ready for review",
  generatedFrom: "10 memories, 38 sensory cues, 4 family themes",
  whoIAm:
    "Robert Ellis is a retired high school history teacher, husband to Elaine, father, and grandfather. He responds strongly to being addressed as Mr. Ellis when discussing teaching, and Robert when family or daily routines are referenced.",
  comforts: [
    "Elaine's voice and references to morning coffee",
    "Soft jazz or old love songs, especially during evening restlessness",
    "Kitchen cues: coffee, pancakes, maple syrup, warm sunlight",
    "Low-stimulation lake imagery with birds and cool morning air",
  ],
  ptCareTeamNotes: [
    "Use music-and-movement memories for gentle mobility: boardwalk dance or living room dance.",
    "During resistance, begin with a familiar role cue: 'Mr. Ellis, can you show me how you stood at the chalkboard?'",
    "For hand exercises, pair with coffee mug or fishing line imagery rather than abstract instructions.",
    "Avoid rushing. Robert responds best when tasks are framed as routines he already knows.",
  ],
  facilityNotes: [
    "Decorate room with family table, classroom, lake, and Elaine photos.",
    "Use Thanksgiving/family table story for mealtime engagement.",
    "If agitated, reduce noise and use Elaine voice story or morning coffee script.",
    "Robert may mention students, Elaine, Michael, or the practice pancake joke.",
  ],
  shareTargets: ["Elaine Ellis - Primary caregiver", "Oakwood Memory Care", "PT / care team handoff"],
};
